-- 코드를 입력하세요
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(REVIEW_SCORE,2) AS SCORE
FROM REST_INFO NATURAL JOIN (SELECT REST_ID, AVG(REVIEW_SCORE) AS REVIEW_SCORE FROM REST_REVIEW GROUP BY REST_ID) A
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY REVIEW_SCORE DESC, FAVORITES DESC